/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Acceleration = {
    Software: 'Software',
    Vaapi: 'Vaapi',
    Cuda: 'Cuda'
} as const;
export type Acceleration = typeof Acceleration[keyof typeof Acceleration];


export function instanceOfAcceleration(value: any): boolean {
    for (const key in Acceleration) {
        if (Object.prototype.hasOwnProperty.call(Acceleration, key)) {
            if (Acceleration[key as keyof typeof Acceleration] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AccelerationFromJSON(json: any): Acceleration {
    return AccelerationFromJSONTyped(json, false);
}

export function AccelerationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Acceleration {
    return json as Acceleration;
}

export function AccelerationToJSON(value?: Acceleration | null): any {
    return value as any;
}

export function AccelerationToJSONTyped(value: any, ignoreDiscriminator: boolean): Acceleration {
    return value as Acceleration;
}

