/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Audioprofile = {
    Low: 'Low',
    Heaac: 'HEAAC',
    Heaacv2: 'HEAACV2'
} as const;
export type Audioprofile = typeof Audioprofile[keyof typeof Audioprofile];


export function instanceOfAudioprofile(value: any): boolean {
    for (const key in Audioprofile) {
        if (Object.prototype.hasOwnProperty.call(Audioprofile, key)) {
            if (Audioprofile[key as keyof typeof Audioprofile] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AudioprofileFromJSON(json: any): Audioprofile {
    return AudioprofileFromJSONTyped(json, false);
}

export function AudioprofileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Audioprofile {
    return json as Audioprofile;
}

export function AudioprofileToJSON(value?: Audioprofile | null): any {
    return value as any;
}

export function AudioprofileToJSONTyped(value: any, ignoreDiscriminator: boolean): Audioprofile {
    return value as Audioprofile;
}

