/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Colorspace = {
    Bt709: 'BT709'
} as const;
export type Colorspace = typeof Colorspace[keyof typeof Colorspace];


export function instanceOfColorspace(value: any): boolean {
    for (const key in Colorspace) {
        if (Object.prototype.hasOwnProperty.call(Colorspace, key)) {
            if (Colorspace[key as keyof typeof Colorspace] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ColorspaceFromJSON(json: any): Colorspace {
    return ColorspaceFromJSONTyped(json, false);
}

export function ColorspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Colorspace {
    return json as Colorspace;
}

export function ColorspaceToJSON(value?: Colorspace | null): any {
    return value as any;
}

export function ColorspaceToJSONTyped(value: any, ignoreDiscriminator: boolean): Colorspace {
    return value as Colorspace;
}

