/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InConfigID
 */
export interface InConfigID {
    /**
     * 
     * @type {string}
     * @memberof InConfigID
     */
    configUid: string;
    /**
     * 
     * @type {string}
     * @memberof InConfigID
     */
    serverUid: string;
}

/**
 * Check if a given object implements the InConfigID interface.
 */
export function instanceOfInConfigID(value: object): value is InConfigID {
    if (!('configUid' in value) || value['configUid'] === undefined) return false;
    if (!('serverUid' in value) || value['serverUid'] === undefined) return false;
    return true;
}

export function InConfigIDFromJSON(json: any): InConfigID {
    return InConfigIDFromJSONTyped(json, false);
}

export function InConfigIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): InConfigID {
    if (json == null) {
        return json;
    }
    return {
        
        'configUid': json['config_uid'],
        'serverUid': json['server_uid'],
    };
}

  export function InConfigIDToJSON(json: any): InConfigID {
      return InConfigIDToJSONTyped(json, false);
  }

  export function InConfigIDToJSONTyped(value?: InConfigID | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config_uid': value['configUid'],
        'server_uid': value['serverUid'],
    };
}

