/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FFConfig } from './FFConfig';
import {
    FFConfigFromJSON,
    FFConfigFromJSONTyped,
    FFConfigToJSON,
    FFConfigToJSONTyped,
} from './FFConfig';

/**
 * 
 * @export
 * @interface InFFUpdate
 */
export interface InFFUpdate {
    /**
     * 
     * @type {FFConfig}
     * @memberof InFFUpdate
     */
    config: FFConfig;
}

/**
 * Check if a given object implements the InFFUpdate interface.
 */
export function instanceOfInFFUpdate(value: object): value is InFFUpdate {
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function InFFUpdateFromJSON(json: any): InFFUpdate {
    return InFFUpdateFromJSONTyped(json, false);
}

export function InFFUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InFFUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'config': FFConfigFromJSON(json['config']),
    };
}

  export function InFFUpdateToJSON(json: any): InFFUpdate {
      return InFFUpdateToJSONTyped(json, false);
  }

  export function InFFUpdateToJSONTyped(value?: InFFUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': FFConfigToJSON(value['config']),
    };
}

