/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { State } from './State';
import {
    StateFromJSON,
    StateFromJSONTyped,
    StateToJSON,
    StateToJSONTyped,
} from './State';
import type { InConfigID } from './InConfigID';
import {
    InConfigIDFromJSON,
    InConfigIDFromJSONTyped,
    InConfigIDToJSON,
    InConfigIDToJSONTyped,
} from './InConfigID';

/**
 * 
 * @export
 * @interface InSetState
 */
export interface InSetState {
    /**
     * 
     * @type {InConfigID}
     * @memberof InSetState
     */
    id: InConfigID;
    /**
     * 
     * @type {State}
     * @memberof InSetState
     */
    state: State;
}



/**
 * Check if a given object implements the InSetState interface.
 */
export function instanceOfInSetState(value: object): value is InSetState {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function InSetStateFromJSON(json: any): InSetState {
    return InSetStateFromJSONTyped(json, false);
}

export function InSetStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InSetState {
    if (json == null) {
        return json;
    }
    return {
        
        'id': InConfigIDFromJSON(json['id']),
        'state': StateFromJSON(json['state']),
    };
}

  export function InSetStateToJSON(json: any): InSetState {
      return InSetStateToJSONTyped(json, false);
  }

  export function InSetStateToJSONTyped(value?: InSetState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': InConfigIDToJSON(value['id']),
        'state': StateToJSON(value['state']),
    };
}

