/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InServerID
 */
export interface InServerID {
    /**
     * 
     * @type {string}
     * @memberof InServerID
     */
    serverUid: string;
}

/**
 * Check if a given object implements the InServerID interface.
 */
export function instanceOfInServerID(value: object): value is InServerID {
    if (!('serverUid' in value) || value['serverUid'] === undefined) return false;
    return true;
}

export function InServerIDFromJSON(json: any): InServerID {
    return InServerIDFromJSONTyped(json, false);
}

export function InServerIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): InServerID {
    if (json == null) {
        return json;
    }
    return {
        
        'serverUid': json['server_uid'],
    };
}

  export function InServerIDToJSON(json: any): InServerID {
      return InServerIDToJSONTyped(json, false);
  }

  export function InServerIDToJSONTyped(value?: InServerID | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'server_uid': value['serverUid'],
    };
}

