/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MPDType = {
    Template: 'Template',
    SegmentTimeline: 'SegmentTimeline'
} as const;
export type MPDType = typeof MPDType[keyof typeof MPDType];


export function instanceOfMPDType(value: any): boolean {
    for (const key in MPDType) {
        if (Object.prototype.hasOwnProperty.call(MPDType, key)) {
            if (MPDType[key as keyof typeof MPDType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MPDTypeFromJSON(json: any): MPDType {
    return MPDTypeFromJSONTyped(json, false);
}

export function MPDTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MPDType {
    return json as MPDType;
}

export function MPDTypeToJSON(value?: MPDType | null): any {
    return value as any;
}

export function MPDTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MPDType {
    return value as MPDType;
}

