/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FFStatusValue } from './FFStatusValue';
import {
    FFStatusValueFromJSON,
    FFStatusValueFromJSONTyped,
    FFStatusValueToJSON,
    FFStatusValueToJSONTyped,
} from './FFStatusValue';

/**
 * 
 * @export
 * @interface OutGetFFStatus
 */
export interface OutGetFFStatus {
    /**
     * 
     * @type {Array<FFStatusValue>}
     * @memberof OutGetFFStatus
     */
    status: Array<FFStatusValue>;
}

/**
 * Check if a given object implements the OutGetFFStatus interface.
 */
export function instanceOfOutGetFFStatus(value: object): value is OutGetFFStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OutGetFFStatusFromJSON(json: any): OutGetFFStatus {
    return OutGetFFStatusFromJSONTyped(json, false);
}

export function OutGetFFStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutGetFFStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ((json['status'] as Array<any>).map(FFStatusValueFromJSON)),
    };
}

  export function OutGetFFStatusToJSON(json: any): OutGetFFStatus {
      return OutGetFFStatusToJSONTyped(json, false);
  }

  export function OutGetFFStatusToJSONTyped(value?: OutGetFFStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ((value['status'] as Array<any>).map(FFStatusValueToJSON)),
    };
}

