/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Server } from './Server';
import {
    ServerFromJSON,
    ServerFromJSONTyped,
    ServerToJSON,
    ServerToJSONTyped,
} from './Server';

/**
 * 
 * @export
 * @interface OutGetAllServers
 */
export interface OutGetAllServers {
    /**
     * 
     * @type {Array<Server>}
     * @memberof OutGetAllServers
     */
    servers: Array<Server>;
}

/**
 * Check if a given object implements the OutGetAllServers interface.
 */
export function instanceOfOutGetAllServers(value: object): value is OutGetAllServers {
    if (!('servers' in value) || value['servers'] === undefined) return false;
    return true;
}

export function OutGetAllServersFromJSON(json: any): OutGetAllServers {
    return OutGetAllServersFromJSONTyped(json, false);
}

export function OutGetAllServersFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutGetAllServers {
    if (json == null) {
        return json;
    }
    return {
        
        'servers': ((json['servers'] as Array<any>).map(ServerFromJSON)),
    };
}

  export function OutGetAllServersToJSON(json: any): OutGetAllServers {
      return OutGetAllServersToJSONTyped(json, false);
  }

  export function OutGetAllServersToJSONTyped(value?: OutGetAllServers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'servers': ((value['servers'] as Array<any>).map(ServerToJSON)),
    };
}

