/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerStatus } from './ServerStatus';
import {
    ServerStatusFromJSON,
    ServerStatusFromJSONTyped,
    ServerStatusToJSON,
    ServerStatusToJSONTyped,
} from './ServerStatus';

/**
 * 
 * @export
 * @interface OutGetAllServerStatus
 */
export interface OutGetAllServerStatus {
    /**
     * 
     * @type {Array<ServerStatus>}
     * @memberof OutGetAllServerStatus
     */
    status: Array<ServerStatus>;
}

/**
 * Check if a given object implements the OutGetAllServerStatus interface.
 */
export function instanceOfOutGetAllServerStatus(value: object): value is OutGetAllServerStatus {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OutGetAllServerStatusFromJSON(json: any): OutGetAllServerStatus {
    return OutGetAllServerStatusFromJSONTyped(json, false);
}

export function OutGetAllServerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutGetAllServerStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'status': ((json['status'] as Array<any>).map(ServerStatusFromJSON)),
    };
}

  export function OutGetAllServerStatusToJSON(json: any): OutGetAllServerStatus {
      return OutGetAllServerStatusToJSONTyped(json, false);
  }

  export function OutGetAllServerStatusToJSONTyped(value?: OutGetAllServerStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': ((value['status'] as Array<any>).map(ServerStatusToJSON)),
    };
}

