/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Log } from './Log';
import {
    LogFromJSON,
    LogFromJSONTyped,
    LogToJSON,
    LogToJSONTyped,
} from './Log';

/**
 * 
 * @export
 * @interface OutGetLogs
 */
export interface OutGetLogs {
    /**
     * 
     * @type {Array<Log>}
     * @memberof OutGetLogs
     */
    logs: Array<Log>;
}

/**
 * Check if a given object implements the OutGetLogs interface.
 */
export function instanceOfOutGetLogs(value: object): value is OutGetLogs {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function OutGetLogsFromJSON(json: any): OutGetLogs {
    return OutGetLogsFromJSONTyped(json, false);
}

export function OutGetLogsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutGetLogs {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': ((json['logs'] as Array<any>).map(LogFromJSON)),
    };
}

  export function OutGetLogsToJSON(json: any): OutGetLogs {
      return OutGetLogsToJSONTyped(json, false);
  }

  export function OutGetLogsToJSONTyped(value?: OutGetLogs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': ((value['logs'] as Array<any>).map(LogToJSON)),
    };
}

