/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Preset = {
    Ultrafast: 'Ultrafast',
    Superfast: 'Superfast',
    Veryfast: 'Veryfast',
    Faster: 'Faster',
    Fast: 'Fast',
    Medium: 'Medium',
    Slow: 'Slow',
    Slower: 'Slower',
    Veryslow: 'Veryslow'
} as const;
export type Preset = typeof Preset[keyof typeof Preset];


export function instanceOfPreset(value: any): boolean {
    for (const key in Preset) {
        if (Object.prototype.hasOwnProperty.call(Preset, key)) {
            if (Preset[key as keyof typeof Preset] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PresetFromJSON(json: any): Preset {
    return PresetFromJSONTyped(json, false);
}

export function PresetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preset {
    return json as Preset;
}

export function PresetToJSON(value?: Preset | null): any {
    return value as any;
}

export function PresetToJSONTyped(value: any, ignoreDiscriminator: boolean): Preset {
    return value as Preset;
}

