/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Profile = {
    Main: 'Main',
    High: 'High',
    High10: 'High10',
    High422: 'High422',
    High444: 'High444'
} as const;
export type Profile = typeof Profile[keyof typeof Profile];


export function instanceOfProfile(value: any): boolean {
    for (const key in Profile) {
        if (Object.prototype.hasOwnProperty.call(Profile, key)) {
            if (Profile[key as keyof typeof Profile] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ProfileFromJSON(json: any): Profile {
    return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
    return json as Profile;
}

export function ProfileToJSON(value?: Profile | null): any {
    return value as any;
}

export function ProfileToJSONTyped(value: any, ignoreDiscriminator: boolean): Profile {
    return value as Profile;
}

