/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoreState } from './CoreState';
import {
    CoreStateFromJSON,
    CoreStateFromJSONTyped,
    CoreStateToJSON,
    CoreStateToJSONTyped,
} from './CoreState';

/**
 * 
 * @export
 * @interface ServerStatus
 */
export interface ServerStatus {
    /**
     * 
     * @type {number}
     * @memberof ServerStatus
     */
    cpuUsage: number;
    /**
     * 
     * @type {CoreState}
     * @memberof ServerStatus
     */
    currentState: CoreState;
    /**
     * 
     * @type {number}
     * @memberof ServerStatus
     */
    memoryUsage: number;
    /**
     * 
     * @type {number}
     * @memberof ServerStatus
     */
    nbCpus: number;
    /**
     * 
     * @type {string}
     * @memberof ServerStatus
     */
    serverUid: string;
    /**
     * 
     * @type {number}
     * @memberof ServerStatus
     */
    totalMemory: number;
}



/**
 * Check if a given object implements the ServerStatus interface.
 */
export function instanceOfServerStatus(value: object): value is ServerStatus {
    if (!('cpuUsage' in value) || value['cpuUsage'] === undefined) return false;
    if (!('currentState' in value) || value['currentState'] === undefined) return false;
    if (!('memoryUsage' in value) || value['memoryUsage'] === undefined) return false;
    if (!('nbCpus' in value) || value['nbCpus'] === undefined) return false;
    if (!('serverUid' in value) || value['serverUid'] === undefined) return false;
    if (!('totalMemory' in value) || value['totalMemory'] === undefined) return false;
    return true;
}

export function ServerStatusFromJSON(json: any): ServerStatus {
    return ServerStatusFromJSONTyped(json, false);
}

export function ServerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'cpuUsage': json['cpu_usage'],
        'currentState': CoreStateFromJSON(json['current_state']),
        'memoryUsage': json['memory_usage'],
        'nbCpus': json['nb_cpus'],
        'serverUid': json['server_uid'],
        'totalMemory': json['total_memory'],
    };
}

  export function ServerStatusToJSON(json: any): ServerStatus {
      return ServerStatusToJSONTyped(json, false);
  }

  export function ServerStatusToJSONTyped(value?: ServerStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_usage': value['cpuUsage'],
        'current_state': CoreStateToJSON(value['currentState']),
        'memory_usage': value['memoryUsage'],
        'nb_cpus': value['nbCpus'],
        'server_uid': value['serverUid'],
        'total_memory': value['totalMemory'],
    };
}

