/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.51
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServerCapability = {
    Transcode: 'Transcode',
    UserInterface: 'UserInterface'
} as const;
export type ServerCapability = typeof ServerCapability[keyof typeof ServerCapability];


export function instanceOfServerCapability(value: any): boolean {
    for (const key in ServerCapability) {
        if (Object.prototype.hasOwnProperty.call(ServerCapability, key)) {
            if (ServerCapability[key as keyof typeof ServerCapability] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServerCapabilityFromJSON(json: any): ServerCapability {
    return ServerCapabilityFromJSONTyped(json, false);
}

export function ServerCapabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerCapability {
    return json as ServerCapability;
}

export function ServerCapabilityToJSON(value?: ServerCapability | null): any {
    return value as any;
}

export function ServerCapabilityToJSONTyped(value: any, ignoreDiscriminator: boolean): ServerCapability {
    return value as ServerCapability;
}

