/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SRTMode = {
    Caller: 'Caller',
    Listener: 'Listener',
    Rendezvous: 'Rendezvous'
} as const;
export type SRTMode = typeof SRTMode[keyof typeof SRTMode];


export function instanceOfSRTMode(value: any): boolean {
    for (const key in SRTMode) {
        if (Object.prototype.hasOwnProperty.call(SRTMode, key)) {
            if (SRTMode[key as keyof typeof SRTMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SRTModeFromJSON(json: any): SRTMode {
    return SRTModeFromJSONTyped(json, false);
}

export function SRTModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SRTMode {
    return json as SRTMode;
}

export function SRTModeToJSON(value?: SRTMode | null): any {
    return value as any;
}

export function SRTModeToJSONTyped(value: any, ignoreDiscriminator: boolean): SRTMode {
    return value as SRTMode;
}

