/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.35
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const VideoEncoder = {
    H264: 'H264',
    Hevc: 'HEVC'
} as const;
export type VideoEncoder = typeof VideoEncoder[keyof typeof VideoEncoder];


export function instanceOfVideoEncoder(value: any): boolean {
    for (const key in VideoEncoder) {
        if (Object.prototype.hasOwnProperty.call(VideoEncoder, key)) {
            if (VideoEncoder[key as keyof typeof VideoEncoder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VideoEncoderFromJSON(json: any): VideoEncoder {
    return VideoEncoderFromJSONTyped(json, false);
}

export function VideoEncoderFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoEncoder {
    return json as VideoEncoder;
}

export function VideoEncoderToJSON(value?: VideoEncoder | null): any {
    return value as any;
}

export function VideoEncoderToJSONTyped(value: any, ignoreDiscriminator: boolean): VideoEncoder {
    return value as VideoEncoder;
}

