/* tslint:disable */
/* eslint-disable */
/**
 * live-cmaf-transcoder
 * API for the Live CMAF Transcoder
 *
 * The version of the OpenAPI document: 0.1.52
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoFilterDeinterlace
 */
export interface VideoFilterDeinterlace {
    /**
     * 
     * @type {boolean}
     * @memberof VideoFilterDeinterlace
     */
    enable: boolean;
}

/**
 * Check if a given object implements the VideoFilterDeinterlace interface.
 */
export function instanceOfVideoFilterDeinterlace(value: object): value is VideoFilterDeinterlace {
    if (!('enable' in value) || value['enable'] === undefined) return false;
    return true;
}

export function VideoFilterDeinterlaceFromJSON(json: any): VideoFilterDeinterlace {
    return VideoFilterDeinterlaceFromJSONTyped(json, false);
}

export function VideoFilterDeinterlaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoFilterDeinterlace {
    if (json == null) {
        return json;
    }
    return {
        
        'enable': json['enable'],
    };
}

  export function VideoFilterDeinterlaceToJSON(json: any): VideoFilterDeinterlace {
      return VideoFilterDeinterlaceToJSONTyped(json, false);
  }

  export function VideoFilterDeinterlaceToJSONTyped(value?: VideoFilterDeinterlace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enable': value['enable'],
    };
}

